CREATE TABLE USUARIO;
(
	ID       INTERGER           PRIMARY KEY,
    NOME         VARCHAR2(80),
    EMAIL        VARCHAR2(80) UNIQUE,
    SENHA        VARCHAR2(150),
    ID_PERMISSAO VARCHAR2(200),
    VALIDADO     NUMBER(1)
);

