CREATE DATABASE USUARIOS;

CREATE TABLE INICIAL
(
    ID           INTEGER PRIMARY KEY,
    NOME         VARCHAR2(60),
    EMAIL        VARCHAR2(100) UNIQUE,
    SENHA        VARCHAR2(500),
    ID_PERMISSAO VARCHAR2(200),
    VALIDADO     NUMBER(1)
);
